# Automatically generated by configure - do not modify
TARGET_NAME=x86_64
TARGET=x86_64-softmmu
EXTRA_CFLAGS=-m64
CC=cc
CCAS=cc
AR=ar
AS=as
LD=ld
NM=nm
OBJCOPY=objcopy
RANLIB=ranlib
STRIP=strip
BUILD_STATIC=
QEMU=/home/ejs1214/SMDK/lib/qemu/qemu-8.1.50/build-femu/qemu-system-x86_64
HOST_GDB_SUPPORTS_ARCH=y
