/* This file is autogenerated by tracetool, do not edit. */

#ifndef TRACE_HW_I2C_GENERATED_TRACERS_H
#define TRACE_HW_I2C_GENERATED_TRACERS_H

#include "trace/control.h"

extern TraceEvent _TRACE_BITBANG_I2C_STATE_EVENT;
extern TraceEvent _TRACE_BITBANG_I2C_ADDR_EVENT;
extern TraceEvent _TRACE_BITBANG_I2C_SEND_EVENT;
extern TraceEvent _TRACE_BITBANG_I2C_RECV_EVENT;
extern TraceEvent _TRACE_BITBANG_I2C_DATA_EVENT;
extern TraceEvent _TRACE_I2C_EVENT_EVENT;
extern TraceEvent _TRACE_I2C_SEND_EVENT;
extern TraceEvent _TRACE_I2C_SEND_ASYNC_EVENT;
extern TraceEvent _TRACE_I2C_RECV_EVENT;
extern TraceEvent _TRACE_I2C_ACK_EVENT;
extern TraceEvent _TRACE_ALLWINNER_I2C_READ_EVENT;
extern TraceEvent _TRACE_ALLWINNER_I2C_WRITE_EVENT;
extern TraceEvent _TRACE_ASPEED_I2C_BUS_CMD_EVENT;
extern TraceEvent _TRACE_ASPEED_I2C_BUS_RAISE_INTERRUPT_EVENT;
extern TraceEvent _TRACE_ASPEED_I2C_BUS_READ_EVENT;
extern TraceEvent _TRACE_ASPEED_I2C_BUS_WRITE_EVENT;
extern TraceEvent _TRACE_ASPEED_I2C_BUS_SEND_EVENT;
extern TraceEvent _TRACE_ASPEED_I2C_BUS_RECV_EVENT;
extern TraceEvent _TRACE_NPCM7XX_SMBUS_READ_EVENT;
extern TraceEvent _TRACE_NPCM7XX_SMBUS_WRITE_EVENT;
extern TraceEvent _TRACE_NPCM7XX_SMBUS_START_EVENT;
extern TraceEvent _TRACE_NPCM7XX_SMBUS_SEND_ADDRESS_EVENT;
extern TraceEvent _TRACE_NPCM7XX_SMBUS_SEND_BYTE_EVENT;
extern TraceEvent _TRACE_NPCM7XX_SMBUS_RECV_BYTE_EVENT;
extern TraceEvent _TRACE_NPCM7XX_SMBUS_STOP_EVENT;
extern TraceEvent _TRACE_NPCM7XX_SMBUS_NACK_EVENT;
extern TraceEvent _TRACE_NPCM7XX_SMBUS_RECV_FIFO_EVENT;
extern TraceEvent _TRACE_PCA954X_WRITE_BYTES_EVENT;
extern TraceEvent _TRACE_PCA954X_READ_DATA_EVENT;
extern TraceEvent _TRACE_I2C_MCTP_TX_START_SEND_EVENT;
extern TraceEvent _TRACE_I2C_MCTP_TX_SEND_BYTE_EVENT;
extern TraceEvent _TRACE_I2C_MCTP_TX_DONE_EVENT;
extern TraceEvent _TRACE_I2C_MCTP_HANDLE_CONTROL_EVENT;
extern TraceEvent _TRACE_I2C_MCTP_UNHANDLED_CONTROL_EVENT;
extern TraceEvent _TRACE_I2C_MCTP_DROP_INVALID_LENGTH_EVENT;
extern TraceEvent _TRACE_I2C_MCTP_DROP_INVALID_PEC_EVENT;
extern TraceEvent _TRACE_I2C_MCTP_DROP_INVALID_EID_EVENT;
extern TraceEvent _TRACE_I2C_MCTP_DROP_INVALID_PKTSEQ_EVENT;
extern TraceEvent _TRACE_I2C_MCTP_DROP_SHORT_PACKET_EVENT;
extern TraceEvent _TRACE_I2C_MCTP_DROP_EXPECTED_SOM_EVENT;
extern uint16_t _TRACE_BITBANG_I2C_STATE_DSTATE;
extern uint16_t _TRACE_BITBANG_I2C_ADDR_DSTATE;
extern uint16_t _TRACE_BITBANG_I2C_SEND_DSTATE;
extern uint16_t _TRACE_BITBANG_I2C_RECV_DSTATE;
extern uint16_t _TRACE_BITBANG_I2C_DATA_DSTATE;
extern uint16_t _TRACE_I2C_EVENT_DSTATE;
extern uint16_t _TRACE_I2C_SEND_DSTATE;
extern uint16_t _TRACE_I2C_SEND_ASYNC_DSTATE;
extern uint16_t _TRACE_I2C_RECV_DSTATE;
extern uint16_t _TRACE_I2C_ACK_DSTATE;
extern uint16_t _TRACE_ALLWINNER_I2C_READ_DSTATE;
extern uint16_t _TRACE_ALLWINNER_I2C_WRITE_DSTATE;
extern uint16_t _TRACE_ASPEED_I2C_BUS_CMD_DSTATE;
extern uint16_t _TRACE_ASPEED_I2C_BUS_RAISE_INTERRUPT_DSTATE;
extern uint16_t _TRACE_ASPEED_I2C_BUS_READ_DSTATE;
extern uint16_t _TRACE_ASPEED_I2C_BUS_WRITE_DSTATE;
extern uint16_t _TRACE_ASPEED_I2C_BUS_SEND_DSTATE;
extern uint16_t _TRACE_ASPEED_I2C_BUS_RECV_DSTATE;
extern uint16_t _TRACE_NPCM7XX_SMBUS_READ_DSTATE;
extern uint16_t _TRACE_NPCM7XX_SMBUS_WRITE_DSTATE;
extern uint16_t _TRACE_NPCM7XX_SMBUS_START_DSTATE;
extern uint16_t _TRACE_NPCM7XX_SMBUS_SEND_ADDRESS_DSTATE;
extern uint16_t _TRACE_NPCM7XX_SMBUS_SEND_BYTE_DSTATE;
extern uint16_t _TRACE_NPCM7XX_SMBUS_RECV_BYTE_DSTATE;
extern uint16_t _TRACE_NPCM7XX_SMBUS_STOP_DSTATE;
extern uint16_t _TRACE_NPCM7XX_SMBUS_NACK_DSTATE;
extern uint16_t _TRACE_NPCM7XX_SMBUS_RECV_FIFO_DSTATE;
extern uint16_t _TRACE_PCA954X_WRITE_BYTES_DSTATE;
extern uint16_t _TRACE_PCA954X_READ_DATA_DSTATE;
extern uint16_t _TRACE_I2C_MCTP_TX_START_SEND_DSTATE;
extern uint16_t _TRACE_I2C_MCTP_TX_SEND_BYTE_DSTATE;
extern uint16_t _TRACE_I2C_MCTP_TX_DONE_DSTATE;
extern uint16_t _TRACE_I2C_MCTP_HANDLE_CONTROL_DSTATE;
extern uint16_t _TRACE_I2C_MCTP_UNHANDLED_CONTROL_DSTATE;
extern uint16_t _TRACE_I2C_MCTP_DROP_INVALID_LENGTH_DSTATE;
extern uint16_t _TRACE_I2C_MCTP_DROP_INVALID_PEC_DSTATE;
extern uint16_t _TRACE_I2C_MCTP_DROP_INVALID_EID_DSTATE;
extern uint16_t _TRACE_I2C_MCTP_DROP_INVALID_PKTSEQ_DSTATE;
extern uint16_t _TRACE_I2C_MCTP_DROP_SHORT_PACKET_DSTATE;
extern uint16_t _TRACE_I2C_MCTP_DROP_EXPECTED_SOM_DSTATE;
#define TRACE_BITBANG_I2C_STATE_ENABLED 1
#define TRACE_BITBANG_I2C_ADDR_ENABLED 1
#define TRACE_BITBANG_I2C_SEND_ENABLED 1
#define TRACE_BITBANG_I2C_RECV_ENABLED 1
#define TRACE_BITBANG_I2C_DATA_ENABLED 1
#define TRACE_I2C_EVENT_ENABLED 1
#define TRACE_I2C_SEND_ENABLED 1
#define TRACE_I2C_SEND_ASYNC_ENABLED 1
#define TRACE_I2C_RECV_ENABLED 1
#define TRACE_I2C_ACK_ENABLED 1
#define TRACE_ALLWINNER_I2C_READ_ENABLED 1
#define TRACE_ALLWINNER_I2C_WRITE_ENABLED 1
#define TRACE_ASPEED_I2C_BUS_CMD_ENABLED 1
#define TRACE_ASPEED_I2C_BUS_RAISE_INTERRUPT_ENABLED 1
#define TRACE_ASPEED_I2C_BUS_READ_ENABLED 1
#define TRACE_ASPEED_I2C_BUS_WRITE_ENABLED 1
#define TRACE_ASPEED_I2C_BUS_SEND_ENABLED 1
#define TRACE_ASPEED_I2C_BUS_RECV_ENABLED 1
#define TRACE_NPCM7XX_SMBUS_READ_ENABLED 1
#define TRACE_NPCM7XX_SMBUS_WRITE_ENABLED 1
#define TRACE_NPCM7XX_SMBUS_START_ENABLED 1
#define TRACE_NPCM7XX_SMBUS_SEND_ADDRESS_ENABLED 1
#define TRACE_NPCM7XX_SMBUS_SEND_BYTE_ENABLED 1
#define TRACE_NPCM7XX_SMBUS_RECV_BYTE_ENABLED 1
#define TRACE_NPCM7XX_SMBUS_STOP_ENABLED 1
#define TRACE_NPCM7XX_SMBUS_NACK_ENABLED 1
#define TRACE_NPCM7XX_SMBUS_RECV_FIFO_ENABLED 1
#define TRACE_PCA954X_WRITE_BYTES_ENABLED 1
#define TRACE_PCA954X_READ_DATA_ENABLED 1
#define TRACE_I2C_MCTP_TX_START_SEND_ENABLED 1
#define TRACE_I2C_MCTP_TX_SEND_BYTE_ENABLED 1
#define TRACE_I2C_MCTP_TX_DONE_ENABLED 1
#define TRACE_I2C_MCTP_HANDLE_CONTROL_ENABLED 1
#define TRACE_I2C_MCTP_UNHANDLED_CONTROL_ENABLED 1
#define TRACE_I2C_MCTP_DROP_INVALID_LENGTH_ENABLED 1
#define TRACE_I2C_MCTP_DROP_INVALID_PEC_ENABLED 1
#define TRACE_I2C_MCTP_DROP_INVALID_EID_ENABLED 1
#define TRACE_I2C_MCTP_DROP_INVALID_PKTSEQ_ENABLED 1
#define TRACE_I2C_MCTP_DROP_SHORT_PACKET_ENABLED 1
#define TRACE_I2C_MCTP_DROP_EXPECTED_SOM_ENABLED 1
#include "qemu/log-for-trace.h"
#include "qemu/error-report.h"


#define TRACE_BITBANG_I2C_STATE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_BITBANG_I2C_STATE) || \
    false)

static inline void _nocheck__trace_bitbang_i2c_state(const char * old_state, const char * new_state)
{
    if (trace_event_get_state(TRACE_BITBANG_I2C_STATE) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 4 "../hw/i2c/trace-events"
            qemu_log("%d@%zu.%06zu:bitbang_i2c_state " "state %s -> %s" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , old_state, new_state);
#line 148 "trace/trace-hw_i2c.h"
        } else {
#line 4 "../hw/i2c/trace-events"
            qemu_log("bitbang_i2c_state " "state %s -> %s" "\n", old_state, new_state);
#line 152 "trace/trace-hw_i2c.h"
        }
    }
}

static inline void trace_bitbang_i2c_state(const char * old_state, const char * new_state)
{
    if (true) {
        _nocheck__trace_bitbang_i2c_state(old_state, new_state);
    }
}

#define TRACE_BITBANG_I2C_ADDR_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_BITBANG_I2C_ADDR) || \
    false)

static inline void _nocheck__trace_bitbang_i2c_addr(uint8_t addr)
{
    if (trace_event_get_state(TRACE_BITBANG_I2C_ADDR) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 5 "../hw/i2c/trace-events"
            qemu_log("%d@%zu.%06zu:bitbang_i2c_addr " "Address 0x%02x" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , addr);
#line 179 "trace/trace-hw_i2c.h"
        } else {
#line 5 "../hw/i2c/trace-events"
            qemu_log("bitbang_i2c_addr " "Address 0x%02x" "\n", addr);
#line 183 "trace/trace-hw_i2c.h"
        }
    }
}

static inline void trace_bitbang_i2c_addr(uint8_t addr)
{
    if (true) {
        _nocheck__trace_bitbang_i2c_addr(addr);
    }
}

#define TRACE_BITBANG_I2C_SEND_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_BITBANG_I2C_SEND) || \
    false)

static inline void _nocheck__trace_bitbang_i2c_send(uint8_t byte)
{
    if (trace_event_get_state(TRACE_BITBANG_I2C_SEND) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 6 "../hw/i2c/trace-events"
            qemu_log("%d@%zu.%06zu:bitbang_i2c_send " "TX byte 0x%02x" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , byte);
#line 210 "trace/trace-hw_i2c.h"
        } else {
#line 6 "../hw/i2c/trace-events"
            qemu_log("bitbang_i2c_send " "TX byte 0x%02x" "\n", byte);
#line 214 "trace/trace-hw_i2c.h"
        }
    }
}

static inline void trace_bitbang_i2c_send(uint8_t byte)
{
    if (true) {
        _nocheck__trace_bitbang_i2c_send(byte);
    }
}

#define TRACE_BITBANG_I2C_RECV_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_BITBANG_I2C_RECV) || \
    false)

static inline void _nocheck__trace_bitbang_i2c_recv(uint8_t byte)
{
    if (trace_event_get_state(TRACE_BITBANG_I2C_RECV) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 7 "../hw/i2c/trace-events"
            qemu_log("%d@%zu.%06zu:bitbang_i2c_recv " "RX byte 0x%02x" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , byte);
#line 241 "trace/trace-hw_i2c.h"
        } else {
#line 7 "../hw/i2c/trace-events"
            qemu_log("bitbang_i2c_recv " "RX byte 0x%02x" "\n", byte);
#line 245 "trace/trace-hw_i2c.h"
        }
    }
}

static inline void trace_bitbang_i2c_recv(uint8_t byte)
{
    if (true) {
        _nocheck__trace_bitbang_i2c_recv(byte);
    }
}

#define TRACE_BITBANG_I2C_DATA_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_BITBANG_I2C_DATA) || \
    false)

static inline void _nocheck__trace_bitbang_i2c_data(unsigned clk, unsigned dat, unsigned old_out, unsigned new_out)
{
    if (trace_event_get_state(TRACE_BITBANG_I2C_DATA) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 8 "../hw/i2c/trace-events"
            qemu_log("%d@%zu.%06zu:bitbang_i2c_data " "clk %u dat %u out %u -> %u" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , clk, dat, old_out, new_out);
#line 272 "trace/trace-hw_i2c.h"
        } else {
#line 8 "../hw/i2c/trace-events"
            qemu_log("bitbang_i2c_data " "clk %u dat %u out %u -> %u" "\n", clk, dat, old_out, new_out);
#line 276 "trace/trace-hw_i2c.h"
        }
    }
}

static inline void trace_bitbang_i2c_data(unsigned clk, unsigned dat, unsigned old_out, unsigned new_out)
{
    if (true) {
        _nocheck__trace_bitbang_i2c_data(clk, dat, old_out, new_out);
    }
}

#define TRACE_I2C_EVENT_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_I2C_EVENT) || \
    false)

static inline void _nocheck__trace_i2c_event(const char * event, uint8_t address)
{
    if (trace_event_get_state(TRACE_I2C_EVENT) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 12 "../hw/i2c/trace-events"
            qemu_log("%d@%zu.%06zu:i2c_event " "%s(addr:0x%02x)" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , event, address);
#line 303 "trace/trace-hw_i2c.h"
        } else {
#line 12 "../hw/i2c/trace-events"
            qemu_log("i2c_event " "%s(addr:0x%02x)" "\n", event, address);
#line 307 "trace/trace-hw_i2c.h"
        }
    }
}

static inline void trace_i2c_event(const char * event, uint8_t address)
{
    if (true) {
        _nocheck__trace_i2c_event(event, address);
    }
}

#define TRACE_I2C_SEND_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_I2C_SEND) || \
    false)

static inline void _nocheck__trace_i2c_send(uint8_t address, uint8_t data)
{
    if (trace_event_get_state(TRACE_I2C_SEND) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 13 "../hw/i2c/trace-events"
            qemu_log("%d@%zu.%06zu:i2c_send " "send(addr:0x%02x) data:0x%02x" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , address, data);
#line 334 "trace/trace-hw_i2c.h"
        } else {
#line 13 "../hw/i2c/trace-events"
            qemu_log("i2c_send " "send(addr:0x%02x) data:0x%02x" "\n", address, data);
#line 338 "trace/trace-hw_i2c.h"
        }
    }
}

static inline void trace_i2c_send(uint8_t address, uint8_t data)
{
    if (true) {
        _nocheck__trace_i2c_send(address, data);
    }
}

#define TRACE_I2C_SEND_ASYNC_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_I2C_SEND_ASYNC) || \
    false)

static inline void _nocheck__trace_i2c_send_async(uint8_t address, uint8_t data)
{
    if (trace_event_get_state(TRACE_I2C_SEND_ASYNC) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 14 "../hw/i2c/trace-events"
            qemu_log("%d@%zu.%06zu:i2c_send_async " "send_async(addr:0x%02x) data:0x%02x" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , address, data);
#line 365 "trace/trace-hw_i2c.h"
        } else {
#line 14 "../hw/i2c/trace-events"
            qemu_log("i2c_send_async " "send_async(addr:0x%02x) data:0x%02x" "\n", address, data);
#line 369 "trace/trace-hw_i2c.h"
        }
    }
}

static inline void trace_i2c_send_async(uint8_t address, uint8_t data)
{
    if (true) {
        _nocheck__trace_i2c_send_async(address, data);
    }
}

#define TRACE_I2C_RECV_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_I2C_RECV) || \
    false)

static inline void _nocheck__trace_i2c_recv(uint8_t address, uint8_t data)
{
    if (trace_event_get_state(TRACE_I2C_RECV) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 15 "../hw/i2c/trace-events"
            qemu_log("%d@%zu.%06zu:i2c_recv " "recv(addr:0x%02x) data:0x%02x" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , address, data);
#line 396 "trace/trace-hw_i2c.h"
        } else {
#line 15 "../hw/i2c/trace-events"
            qemu_log("i2c_recv " "recv(addr:0x%02x) data:0x%02x" "\n", address, data);
#line 400 "trace/trace-hw_i2c.h"
        }
    }
}

static inline void trace_i2c_recv(uint8_t address, uint8_t data)
{
    if (true) {
        _nocheck__trace_i2c_recv(address, data);
    }
}

#define TRACE_I2C_ACK_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_I2C_ACK) || \
    false)

static inline void _nocheck__trace_i2c_ack(void)
{
    if (trace_event_get_state(TRACE_I2C_ACK) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 16 "../hw/i2c/trace-events"
            qemu_log("%d@%zu.%06zu:i2c_ack " "" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     );
#line 427 "trace/trace-hw_i2c.h"
        } else {
#line 16 "../hw/i2c/trace-events"
            qemu_log("i2c_ack " "" "\n");
#line 431 "trace/trace-hw_i2c.h"
        }
    }
}

static inline void trace_i2c_ack(void)
{
    if (true) {
        _nocheck__trace_i2c_ack();
    }
}

#define TRACE_ALLWINNER_I2C_READ_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ALLWINNER_I2C_READ) || \
    false)

static inline void _nocheck__trace_allwinner_i2c_read(const char* reg_name, uint64_t offset, uint64_t value)
{
    if (trace_event_get_state(TRACE_ALLWINNER_I2C_READ) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 20 "../hw/i2c/trace-events"
            qemu_log("%d@%zu.%06zu:allwinner_i2c_read " "read %s [0x%" PRIx64 "]: -> 0x%" PRIx64 "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , reg_name, offset, value);
#line 458 "trace/trace-hw_i2c.h"
        } else {
#line 20 "../hw/i2c/trace-events"
            qemu_log("allwinner_i2c_read " "read %s [0x%" PRIx64 "]: -> 0x%" PRIx64 "\n", reg_name, offset, value);
#line 462 "trace/trace-hw_i2c.h"
        }
    }
}

static inline void trace_allwinner_i2c_read(const char* reg_name, uint64_t offset, uint64_t value)
{
    if (true) {
        _nocheck__trace_allwinner_i2c_read(reg_name, offset, value);
    }
}

#define TRACE_ALLWINNER_I2C_WRITE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ALLWINNER_I2C_WRITE) || \
    false)

static inline void _nocheck__trace_allwinner_i2c_write(const char* reg_name, uint64_t offset, uint64_t value)
{
    if (trace_event_get_state(TRACE_ALLWINNER_I2C_WRITE) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 21 "../hw/i2c/trace-events"
            qemu_log("%d@%zu.%06zu:allwinner_i2c_write " "write %s [0x%" PRIx64 "]: <- 0x%" PRIx64 "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , reg_name, offset, value);
#line 489 "trace/trace-hw_i2c.h"
        } else {
#line 21 "../hw/i2c/trace-events"
            qemu_log("allwinner_i2c_write " "write %s [0x%" PRIx64 "]: <- 0x%" PRIx64 "\n", reg_name, offset, value);
#line 493 "trace/trace-hw_i2c.h"
        }
    }
}

static inline void trace_allwinner_i2c_write(const char* reg_name, uint64_t offset, uint64_t value)
{
    if (true) {
        _nocheck__trace_allwinner_i2c_write(reg_name, offset, value);
    }
}

#define TRACE_ASPEED_I2C_BUS_CMD_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ASPEED_I2C_BUS_CMD) || \
    false)

static inline void _nocheck__trace_aspeed_i2c_bus_cmd(uint32_t cmd, const char * cmd_flags, uint32_t count, uint32_t intr_status)
{
    if (trace_event_get_state(TRACE_ASPEED_I2C_BUS_CMD) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 25 "../hw/i2c/trace-events"
            qemu_log("%d@%zu.%06zu:aspeed_i2c_bus_cmd " "handling cmd=0x%x %s count=%d intr=0x%x" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , cmd, cmd_flags, count, intr_status);
#line 520 "trace/trace-hw_i2c.h"
        } else {
#line 25 "../hw/i2c/trace-events"
            qemu_log("aspeed_i2c_bus_cmd " "handling cmd=0x%x %s count=%d intr=0x%x" "\n", cmd, cmd_flags, count, intr_status);
#line 524 "trace/trace-hw_i2c.h"
        }
    }
}

static inline void trace_aspeed_i2c_bus_cmd(uint32_t cmd, const char * cmd_flags, uint32_t count, uint32_t intr_status)
{
    if (true) {
        _nocheck__trace_aspeed_i2c_bus_cmd(cmd, cmd_flags, count, intr_status);
    }
}

#define TRACE_ASPEED_I2C_BUS_RAISE_INTERRUPT_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ASPEED_I2C_BUS_RAISE_INTERRUPT) || \
    false)

static inline void _nocheck__trace_aspeed_i2c_bus_raise_interrupt(uint32_t intr_status, const char * s)
{
    if (trace_event_get_state(TRACE_ASPEED_I2C_BUS_RAISE_INTERRUPT) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 26 "../hw/i2c/trace-events"
            qemu_log("%d@%zu.%06zu:aspeed_i2c_bus_raise_interrupt " "handled intr=0x%x %s" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , intr_status, s);
#line 551 "trace/trace-hw_i2c.h"
        } else {
#line 26 "../hw/i2c/trace-events"
            qemu_log("aspeed_i2c_bus_raise_interrupt " "handled intr=0x%x %s" "\n", intr_status, s);
#line 555 "trace/trace-hw_i2c.h"
        }
    }
}

static inline void trace_aspeed_i2c_bus_raise_interrupt(uint32_t intr_status, const char * s)
{
    if (true) {
        _nocheck__trace_aspeed_i2c_bus_raise_interrupt(intr_status, s);
    }
}

#define TRACE_ASPEED_I2C_BUS_READ_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ASPEED_I2C_BUS_READ) || \
    false)

static inline void _nocheck__trace_aspeed_i2c_bus_read(uint32_t busid, uint64_t offset, unsigned size, uint64_t value)
{
    if (trace_event_get_state(TRACE_ASPEED_I2C_BUS_READ) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 27 "../hw/i2c/trace-events"
            qemu_log("%d@%zu.%06zu:aspeed_i2c_bus_read " "bus[%d]: To 0x%" PRIx64 " of size %u: 0x%" PRIx64 "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , busid, offset, size, value);
#line 582 "trace/trace-hw_i2c.h"
        } else {
#line 27 "../hw/i2c/trace-events"
            qemu_log("aspeed_i2c_bus_read " "bus[%d]: To 0x%" PRIx64 " of size %u: 0x%" PRIx64 "\n", busid, offset, size, value);
#line 586 "trace/trace-hw_i2c.h"
        }
    }
}

static inline void trace_aspeed_i2c_bus_read(uint32_t busid, uint64_t offset, unsigned size, uint64_t value)
{
    if (true) {
        _nocheck__trace_aspeed_i2c_bus_read(busid, offset, size, value);
    }
}

#define TRACE_ASPEED_I2C_BUS_WRITE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ASPEED_I2C_BUS_WRITE) || \
    false)

static inline void _nocheck__trace_aspeed_i2c_bus_write(uint32_t busid, uint64_t offset, unsigned size, uint64_t value)
{
    if (trace_event_get_state(TRACE_ASPEED_I2C_BUS_WRITE) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 28 "../hw/i2c/trace-events"
            qemu_log("%d@%zu.%06zu:aspeed_i2c_bus_write " "bus[%d]: To 0x%" PRIx64 " of size %u: 0x%" PRIx64 "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , busid, offset, size, value);
#line 613 "trace/trace-hw_i2c.h"
        } else {
#line 28 "../hw/i2c/trace-events"
            qemu_log("aspeed_i2c_bus_write " "bus[%d]: To 0x%" PRIx64 " of size %u: 0x%" PRIx64 "\n", busid, offset, size, value);
#line 617 "trace/trace-hw_i2c.h"
        }
    }
}

static inline void trace_aspeed_i2c_bus_write(uint32_t busid, uint64_t offset, unsigned size, uint64_t value)
{
    if (true) {
        _nocheck__trace_aspeed_i2c_bus_write(busid, offset, size, value);
    }
}

#define TRACE_ASPEED_I2C_BUS_SEND_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ASPEED_I2C_BUS_SEND) || \
    false)

static inline void _nocheck__trace_aspeed_i2c_bus_send(const char * mode, int i, int count, uint8_t byte)
{
    if (trace_event_get_state(TRACE_ASPEED_I2C_BUS_SEND) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 29 "../hw/i2c/trace-events"
            qemu_log("%d@%zu.%06zu:aspeed_i2c_bus_send " "%s send %d/%d 0x%02x" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , mode, i, count, byte);
#line 644 "trace/trace-hw_i2c.h"
        } else {
#line 29 "../hw/i2c/trace-events"
            qemu_log("aspeed_i2c_bus_send " "%s send %d/%d 0x%02x" "\n", mode, i, count, byte);
#line 648 "trace/trace-hw_i2c.h"
        }
    }
}

static inline void trace_aspeed_i2c_bus_send(const char * mode, int i, int count, uint8_t byte)
{
    if (true) {
        _nocheck__trace_aspeed_i2c_bus_send(mode, i, count, byte);
    }
}

#define TRACE_ASPEED_I2C_BUS_RECV_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ASPEED_I2C_BUS_RECV) || \
    false)

static inline void _nocheck__trace_aspeed_i2c_bus_recv(const char * mode, int i, int count, uint8_t byte)
{
    if (trace_event_get_state(TRACE_ASPEED_I2C_BUS_RECV) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 30 "../hw/i2c/trace-events"
            qemu_log("%d@%zu.%06zu:aspeed_i2c_bus_recv " "%s recv %d/%d 0x%02x" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , mode, i, count, byte);
#line 675 "trace/trace-hw_i2c.h"
        } else {
#line 30 "../hw/i2c/trace-events"
            qemu_log("aspeed_i2c_bus_recv " "%s recv %d/%d 0x%02x" "\n", mode, i, count, byte);
#line 679 "trace/trace-hw_i2c.h"
        }
    }
}

static inline void trace_aspeed_i2c_bus_recv(const char * mode, int i, int count, uint8_t byte)
{
    if (true) {
        _nocheck__trace_aspeed_i2c_bus_recv(mode, i, count, byte);
    }
}

#define TRACE_NPCM7XX_SMBUS_READ_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_NPCM7XX_SMBUS_READ) || \
    false)

static inline void _nocheck__trace_npcm7xx_smbus_read(const char * id, uint64_t offset, uint64_t value, unsigned size)
{
    if (trace_event_get_state(TRACE_NPCM7XX_SMBUS_READ) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 34 "../hw/i2c/trace-events"
            qemu_log("%d@%zu.%06zu:npcm7xx_smbus_read " "%s offset: 0x%04" PRIx64 " value: 0x%02" PRIx64 " size: %u" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , id, offset, value, size);
#line 706 "trace/trace-hw_i2c.h"
        } else {
#line 34 "../hw/i2c/trace-events"
            qemu_log("npcm7xx_smbus_read " "%s offset: 0x%04" PRIx64 " value: 0x%02" PRIx64 " size: %u" "\n", id, offset, value, size);
#line 710 "trace/trace-hw_i2c.h"
        }
    }
}

static inline void trace_npcm7xx_smbus_read(const char * id, uint64_t offset, uint64_t value, unsigned size)
{
    if (true) {
        _nocheck__trace_npcm7xx_smbus_read(id, offset, value, size);
    }
}

#define TRACE_NPCM7XX_SMBUS_WRITE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_NPCM7XX_SMBUS_WRITE) || \
    false)

static inline void _nocheck__trace_npcm7xx_smbus_write(const char * id, uint64_t offset, uint64_t value, unsigned size)
{
    if (trace_event_get_state(TRACE_NPCM7XX_SMBUS_WRITE) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 35 "../hw/i2c/trace-events"
            qemu_log("%d@%zu.%06zu:npcm7xx_smbus_write " "%s offset: 0x%04" PRIx64 " value: 0x%02" PRIx64 " size: %u" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , id, offset, value, size);
#line 737 "trace/trace-hw_i2c.h"
        } else {
#line 35 "../hw/i2c/trace-events"
            qemu_log("npcm7xx_smbus_write " "%s offset: 0x%04" PRIx64 " value: 0x%02" PRIx64 " size: %u" "\n", id, offset, value, size);
#line 741 "trace/trace-hw_i2c.h"
        }
    }
}

static inline void trace_npcm7xx_smbus_write(const char * id, uint64_t offset, uint64_t value, unsigned size)
{
    if (true) {
        _nocheck__trace_npcm7xx_smbus_write(id, offset, value, size);
    }
}

#define TRACE_NPCM7XX_SMBUS_START_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_NPCM7XX_SMBUS_START) || \
    false)

static inline void _nocheck__trace_npcm7xx_smbus_start(const char * id, int success)
{
    if (trace_event_get_state(TRACE_NPCM7XX_SMBUS_START) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 36 "../hw/i2c/trace-events"
            qemu_log("%d@%zu.%06zu:npcm7xx_smbus_start " "%s starting, success: %d" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , id, success);
#line 768 "trace/trace-hw_i2c.h"
        } else {
#line 36 "../hw/i2c/trace-events"
            qemu_log("npcm7xx_smbus_start " "%s starting, success: %d" "\n", id, success);
#line 772 "trace/trace-hw_i2c.h"
        }
    }
}

static inline void trace_npcm7xx_smbus_start(const char * id, int success)
{
    if (true) {
        _nocheck__trace_npcm7xx_smbus_start(id, success);
    }
}

#define TRACE_NPCM7XX_SMBUS_SEND_ADDRESS_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_NPCM7XX_SMBUS_SEND_ADDRESS) || \
    false)

static inline void _nocheck__trace_npcm7xx_smbus_send_address(const char * id, uint8_t addr, int recv, int success)
{
    if (trace_event_get_state(TRACE_NPCM7XX_SMBUS_SEND_ADDRESS) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 37 "../hw/i2c/trace-events"
            qemu_log("%d@%zu.%06zu:npcm7xx_smbus_send_address " "%s sending address: 0x%02x, recv: %d, success: %d" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , id, addr, recv, success);
#line 799 "trace/trace-hw_i2c.h"
        } else {
#line 37 "../hw/i2c/trace-events"
            qemu_log("npcm7xx_smbus_send_address " "%s sending address: 0x%02x, recv: %d, success: %d" "\n", id, addr, recv, success);
#line 803 "trace/trace-hw_i2c.h"
        }
    }
}

static inline void trace_npcm7xx_smbus_send_address(const char * id, uint8_t addr, int recv, int success)
{
    if (true) {
        _nocheck__trace_npcm7xx_smbus_send_address(id, addr, recv, success);
    }
}

#define TRACE_NPCM7XX_SMBUS_SEND_BYTE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_NPCM7XX_SMBUS_SEND_BYTE) || \
    false)

static inline void _nocheck__trace_npcm7xx_smbus_send_byte(const char * id, uint8_t value, int success)
{
    if (trace_event_get_state(TRACE_NPCM7XX_SMBUS_SEND_BYTE) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 38 "../hw/i2c/trace-events"
            qemu_log("%d@%zu.%06zu:npcm7xx_smbus_send_byte " "%s send byte: 0x%02x, success: %d" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , id, value, success);
#line 830 "trace/trace-hw_i2c.h"
        } else {
#line 38 "../hw/i2c/trace-events"
            qemu_log("npcm7xx_smbus_send_byte " "%s send byte: 0x%02x, success: %d" "\n", id, value, success);
#line 834 "trace/trace-hw_i2c.h"
        }
    }
}

static inline void trace_npcm7xx_smbus_send_byte(const char * id, uint8_t value, int success)
{
    if (true) {
        _nocheck__trace_npcm7xx_smbus_send_byte(id, value, success);
    }
}

#define TRACE_NPCM7XX_SMBUS_RECV_BYTE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_NPCM7XX_SMBUS_RECV_BYTE) || \
    false)

static inline void _nocheck__trace_npcm7xx_smbus_recv_byte(const char * id, uint8_t value)
{
    if (trace_event_get_state(TRACE_NPCM7XX_SMBUS_RECV_BYTE) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 39 "../hw/i2c/trace-events"
            qemu_log("%d@%zu.%06zu:npcm7xx_smbus_recv_byte " "%s recv byte: 0x%02x" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , id, value);
#line 861 "trace/trace-hw_i2c.h"
        } else {
#line 39 "../hw/i2c/trace-events"
            qemu_log("npcm7xx_smbus_recv_byte " "%s recv byte: 0x%02x" "\n", id, value);
#line 865 "trace/trace-hw_i2c.h"
        }
    }
}

static inline void trace_npcm7xx_smbus_recv_byte(const char * id, uint8_t value)
{
    if (true) {
        _nocheck__trace_npcm7xx_smbus_recv_byte(id, value);
    }
}

#define TRACE_NPCM7XX_SMBUS_STOP_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_NPCM7XX_SMBUS_STOP) || \
    false)

static inline void _nocheck__trace_npcm7xx_smbus_stop(const char * id)
{
    if (trace_event_get_state(TRACE_NPCM7XX_SMBUS_STOP) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 40 "../hw/i2c/trace-events"
            qemu_log("%d@%zu.%06zu:npcm7xx_smbus_stop " "%s stopping" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , id);
#line 892 "trace/trace-hw_i2c.h"
        } else {
#line 40 "../hw/i2c/trace-events"
            qemu_log("npcm7xx_smbus_stop " "%s stopping" "\n", id);
#line 896 "trace/trace-hw_i2c.h"
        }
    }
}

static inline void trace_npcm7xx_smbus_stop(const char * id)
{
    if (true) {
        _nocheck__trace_npcm7xx_smbus_stop(id);
    }
}

#define TRACE_NPCM7XX_SMBUS_NACK_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_NPCM7XX_SMBUS_NACK) || \
    false)

static inline void _nocheck__trace_npcm7xx_smbus_nack(const char * id)
{
    if (trace_event_get_state(TRACE_NPCM7XX_SMBUS_NACK) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 41 "../hw/i2c/trace-events"
            qemu_log("%d@%zu.%06zu:npcm7xx_smbus_nack " "%s nacking" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , id);
#line 923 "trace/trace-hw_i2c.h"
        } else {
#line 41 "../hw/i2c/trace-events"
            qemu_log("npcm7xx_smbus_nack " "%s nacking" "\n", id);
#line 927 "trace/trace-hw_i2c.h"
        }
    }
}

static inline void trace_npcm7xx_smbus_nack(const char * id)
{
    if (true) {
        _nocheck__trace_npcm7xx_smbus_nack(id);
    }
}

#define TRACE_NPCM7XX_SMBUS_RECV_FIFO_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_NPCM7XX_SMBUS_RECV_FIFO) || \
    false)

static inline void _nocheck__trace_npcm7xx_smbus_recv_fifo(const char * id, uint8_t received, uint8_t expected)
{
    if (trace_event_get_state(TRACE_NPCM7XX_SMBUS_RECV_FIFO) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 42 "../hw/i2c/trace-events"
            qemu_log("%d@%zu.%06zu:npcm7xx_smbus_recv_fifo " "%s recv fifo: received %u, expected %u" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , id, received, expected);
#line 954 "trace/trace-hw_i2c.h"
        } else {
#line 42 "../hw/i2c/trace-events"
            qemu_log("npcm7xx_smbus_recv_fifo " "%s recv fifo: received %u, expected %u" "\n", id, received, expected);
#line 958 "trace/trace-hw_i2c.h"
        }
    }
}

static inline void trace_npcm7xx_smbus_recv_fifo(const char * id, uint8_t received, uint8_t expected)
{
    if (true) {
        _nocheck__trace_npcm7xx_smbus_recv_fifo(id, received, expected);
    }
}

#define TRACE_PCA954X_WRITE_BYTES_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_PCA954X_WRITE_BYTES) || \
    false)

static inline void _nocheck__trace_pca954x_write_bytes(uint8_t value)
{
    if (trace_event_get_state(TRACE_PCA954X_WRITE_BYTES) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 46 "../hw/i2c/trace-events"
            qemu_log("%d@%zu.%06zu:pca954x_write_bytes " "PCA954X write data: 0x%02x" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , value);
#line 985 "trace/trace-hw_i2c.h"
        } else {
#line 46 "../hw/i2c/trace-events"
            qemu_log("pca954x_write_bytes " "PCA954X write data: 0x%02x" "\n", value);
#line 989 "trace/trace-hw_i2c.h"
        }
    }
}

static inline void trace_pca954x_write_bytes(uint8_t value)
{
    if (true) {
        _nocheck__trace_pca954x_write_bytes(value);
    }
}

#define TRACE_PCA954X_READ_DATA_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_PCA954X_READ_DATA) || \
    false)

static inline void _nocheck__trace_pca954x_read_data(uint8_t value)
{
    if (trace_event_get_state(TRACE_PCA954X_READ_DATA) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 47 "../hw/i2c/trace-events"
            qemu_log("%d@%zu.%06zu:pca954x_read_data " "PCA954X read data: 0x%02x" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , value);
#line 1016 "trace/trace-hw_i2c.h"
        } else {
#line 47 "../hw/i2c/trace-events"
            qemu_log("pca954x_read_data " "PCA954X read data: 0x%02x" "\n", value);
#line 1020 "trace/trace-hw_i2c.h"
        }
    }
}

static inline void trace_pca954x_read_data(uint8_t value)
{
    if (true) {
        _nocheck__trace_pca954x_read_data(value);
    }
}

#define TRACE_I2C_MCTP_TX_START_SEND_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_I2C_MCTP_TX_START_SEND) || \
    false)

static inline void _nocheck__trace_i2c_mctp_tx_start_send(size_t len)
{
    if (trace_event_get_state(TRACE_I2C_MCTP_TX_START_SEND) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 50 "../hw/i2c/trace-events"
            qemu_log("%d@%zu.%06zu:i2c_mctp_tx_start_send " "len %zu" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , len);
#line 1047 "trace/trace-hw_i2c.h"
        } else {
#line 50 "../hw/i2c/trace-events"
            qemu_log("i2c_mctp_tx_start_send " "len %zu" "\n", len);
#line 1051 "trace/trace-hw_i2c.h"
        }
    }
}

static inline void trace_i2c_mctp_tx_start_send(size_t len)
{
    if (true) {
        _nocheck__trace_i2c_mctp_tx_start_send(len);
    }
}

#define TRACE_I2C_MCTP_TX_SEND_BYTE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_I2C_MCTP_TX_SEND_BYTE) || \
    false)

static inline void _nocheck__trace_i2c_mctp_tx_send_byte(size_t pos, uint8_t byte)
{
    if (trace_event_get_state(TRACE_I2C_MCTP_TX_SEND_BYTE) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 51 "../hw/i2c/trace-events"
            qemu_log("%d@%zu.%06zu:i2c_mctp_tx_send_byte " "pos %zu byte 0x%"PRIx8"" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , pos, byte);
#line 1078 "trace/trace-hw_i2c.h"
        } else {
#line 51 "../hw/i2c/trace-events"
            qemu_log("i2c_mctp_tx_send_byte " "pos %zu byte 0x%"PRIx8"" "\n", pos, byte);
#line 1082 "trace/trace-hw_i2c.h"
        }
    }
}

static inline void trace_i2c_mctp_tx_send_byte(size_t pos, uint8_t byte)
{
    if (true) {
        _nocheck__trace_i2c_mctp_tx_send_byte(pos, byte);
    }
}

#define TRACE_I2C_MCTP_TX_DONE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_I2C_MCTP_TX_DONE) || \
    false)

static inline void _nocheck__trace_i2c_mctp_tx_done(void)
{
    if (trace_event_get_state(TRACE_I2C_MCTP_TX_DONE) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 52 "../hw/i2c/trace-events"
            qemu_log("%d@%zu.%06zu:i2c_mctp_tx_done " "packet sent" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     );
#line 1109 "trace/trace-hw_i2c.h"
        } else {
#line 52 "../hw/i2c/trace-events"
            qemu_log("i2c_mctp_tx_done " "packet sent" "\n");
#line 1113 "trace/trace-hw_i2c.h"
        }
    }
}

static inline void trace_i2c_mctp_tx_done(void)
{
    if (true) {
        _nocheck__trace_i2c_mctp_tx_done();
    }
}

#define TRACE_I2C_MCTP_HANDLE_CONTROL_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_I2C_MCTP_HANDLE_CONTROL) || \
    false)

static inline void _nocheck__trace_i2c_mctp_handle_control(uint8_t command)
{
    if (trace_event_get_state(TRACE_I2C_MCTP_HANDLE_CONTROL) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 53 "../hw/i2c/trace-events"
            qemu_log("%d@%zu.%06zu:i2c_mctp_handle_control " "command 0x%"PRIx8"" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , command);
#line 1140 "trace/trace-hw_i2c.h"
        } else {
#line 53 "../hw/i2c/trace-events"
            qemu_log("i2c_mctp_handle_control " "command 0x%"PRIx8"" "\n", command);
#line 1144 "trace/trace-hw_i2c.h"
        }
    }
}

static inline void trace_i2c_mctp_handle_control(uint8_t command)
{
    if (true) {
        _nocheck__trace_i2c_mctp_handle_control(command);
    }
}

#define TRACE_I2C_MCTP_UNHANDLED_CONTROL_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_I2C_MCTP_UNHANDLED_CONTROL) || \
    false)

static inline void _nocheck__trace_i2c_mctp_unhandled_control(uint8_t command)
{
    if (trace_event_get_state(TRACE_I2C_MCTP_UNHANDLED_CONTROL) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 54 "../hw/i2c/trace-events"
            qemu_log("%d@%zu.%06zu:i2c_mctp_unhandled_control " "command 0x%"PRIx8"" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , command);
#line 1171 "trace/trace-hw_i2c.h"
        } else {
#line 54 "../hw/i2c/trace-events"
            qemu_log("i2c_mctp_unhandled_control " "command 0x%"PRIx8"" "\n", command);
#line 1175 "trace/trace-hw_i2c.h"
        }
    }
}

static inline void trace_i2c_mctp_unhandled_control(uint8_t command)
{
    if (true) {
        _nocheck__trace_i2c_mctp_unhandled_control(command);
    }
}

#define TRACE_I2C_MCTP_DROP_INVALID_LENGTH_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_I2C_MCTP_DROP_INVALID_LENGTH) || \
    false)

static inline void _nocheck__trace_i2c_mctp_drop_invalid_length(unsigned byte_count, size_t expected)
{
    if (trace_event_get_state(TRACE_I2C_MCTP_DROP_INVALID_LENGTH) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 55 "../hw/i2c/trace-events"
            qemu_log("%d@%zu.%06zu:i2c_mctp_drop_invalid_length " "byte_count %u expected %zu" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , byte_count, expected);
#line 1202 "trace/trace-hw_i2c.h"
        } else {
#line 55 "../hw/i2c/trace-events"
            qemu_log("i2c_mctp_drop_invalid_length " "byte_count %u expected %zu" "\n", byte_count, expected);
#line 1206 "trace/trace-hw_i2c.h"
        }
    }
}

static inline void trace_i2c_mctp_drop_invalid_length(unsigned byte_count, size_t expected)
{
    if (true) {
        _nocheck__trace_i2c_mctp_drop_invalid_length(byte_count, expected);
    }
}

#define TRACE_I2C_MCTP_DROP_INVALID_PEC_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_I2C_MCTP_DROP_INVALID_PEC) || \
    false)

static inline void _nocheck__trace_i2c_mctp_drop_invalid_pec(uint8_t pec, uint8_t expected)
{
    if (trace_event_get_state(TRACE_I2C_MCTP_DROP_INVALID_PEC) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 56 "../hw/i2c/trace-events"
            qemu_log("%d@%zu.%06zu:i2c_mctp_drop_invalid_pec " "pec 0x%"PRIx8" expected 0x%"PRIx8"" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , pec, expected);
#line 1233 "trace/trace-hw_i2c.h"
        } else {
#line 56 "../hw/i2c/trace-events"
            qemu_log("i2c_mctp_drop_invalid_pec " "pec 0x%"PRIx8" expected 0x%"PRIx8"" "\n", pec, expected);
#line 1237 "trace/trace-hw_i2c.h"
        }
    }
}

static inline void trace_i2c_mctp_drop_invalid_pec(uint8_t pec, uint8_t expected)
{
    if (true) {
        _nocheck__trace_i2c_mctp_drop_invalid_pec(pec, expected);
    }
}

#define TRACE_I2C_MCTP_DROP_INVALID_EID_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_I2C_MCTP_DROP_INVALID_EID) || \
    false)

static inline void _nocheck__trace_i2c_mctp_drop_invalid_eid(uint8_t eid, uint8_t expected)
{
    if (trace_event_get_state(TRACE_I2C_MCTP_DROP_INVALID_EID) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 57 "../hw/i2c/trace-events"
            qemu_log("%d@%zu.%06zu:i2c_mctp_drop_invalid_eid " "eid 0x%"PRIx8" expected 0x%"PRIx8"" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , eid, expected);
#line 1264 "trace/trace-hw_i2c.h"
        } else {
#line 57 "../hw/i2c/trace-events"
            qemu_log("i2c_mctp_drop_invalid_eid " "eid 0x%"PRIx8" expected 0x%"PRIx8"" "\n", eid, expected);
#line 1268 "trace/trace-hw_i2c.h"
        }
    }
}

static inline void trace_i2c_mctp_drop_invalid_eid(uint8_t eid, uint8_t expected)
{
    if (true) {
        _nocheck__trace_i2c_mctp_drop_invalid_eid(eid, expected);
    }
}

#define TRACE_I2C_MCTP_DROP_INVALID_PKTSEQ_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_I2C_MCTP_DROP_INVALID_PKTSEQ) || \
    false)

static inline void _nocheck__trace_i2c_mctp_drop_invalid_pktseq(uint8_t pktseq, uint8_t expected)
{
    if (trace_event_get_state(TRACE_I2C_MCTP_DROP_INVALID_PKTSEQ) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 58 "../hw/i2c/trace-events"
            qemu_log("%d@%zu.%06zu:i2c_mctp_drop_invalid_pktseq " "pktseq 0x%"PRIx8" expected 0x%"PRIx8"" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , pktseq, expected);
#line 1295 "trace/trace-hw_i2c.h"
        } else {
#line 58 "../hw/i2c/trace-events"
            qemu_log("i2c_mctp_drop_invalid_pktseq " "pktseq 0x%"PRIx8" expected 0x%"PRIx8"" "\n", pktseq, expected);
#line 1299 "trace/trace-hw_i2c.h"
        }
    }
}

static inline void trace_i2c_mctp_drop_invalid_pktseq(uint8_t pktseq, uint8_t expected)
{
    if (true) {
        _nocheck__trace_i2c_mctp_drop_invalid_pktseq(pktseq, expected);
    }
}

#define TRACE_I2C_MCTP_DROP_SHORT_PACKET_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_I2C_MCTP_DROP_SHORT_PACKET) || \
    false)

static inline void _nocheck__trace_i2c_mctp_drop_short_packet(size_t len)
{
    if (trace_event_get_state(TRACE_I2C_MCTP_DROP_SHORT_PACKET) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 59 "../hw/i2c/trace-events"
            qemu_log("%d@%zu.%06zu:i2c_mctp_drop_short_packet " "len %zu" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , len);
#line 1326 "trace/trace-hw_i2c.h"
        } else {
#line 59 "../hw/i2c/trace-events"
            qemu_log("i2c_mctp_drop_short_packet " "len %zu" "\n", len);
#line 1330 "trace/trace-hw_i2c.h"
        }
    }
}

static inline void trace_i2c_mctp_drop_short_packet(size_t len)
{
    if (true) {
        _nocheck__trace_i2c_mctp_drop_short_packet(len);
    }
}

#define TRACE_I2C_MCTP_DROP_EXPECTED_SOM_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_I2C_MCTP_DROP_EXPECTED_SOM) || \
    false)

static inline void _nocheck__trace_i2c_mctp_drop_expected_som(void)
{
    if (trace_event_get_state(TRACE_I2C_MCTP_DROP_EXPECTED_SOM) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 60 "../hw/i2c/trace-events"
            qemu_log("%d@%zu.%06zu:i2c_mctp_drop_expected_som " "" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     );
#line 1357 "trace/trace-hw_i2c.h"
        } else {
#line 60 "../hw/i2c/trace-events"
            qemu_log("i2c_mctp_drop_expected_som " "" "\n");
#line 1361 "trace/trace-hw_i2c.h"
        }
    }
}

static inline void trace_i2c_mctp_drop_expected_som(void)
{
    if (true) {
        _nocheck__trace_i2c_mctp_drop_expected_som();
    }
}
#endif /* TRACE_HW_I2C_GENERATED_TRACERS_H */
