# Automatically generated by configure - do not modify

all:
SRC_PATH=/home/ejs1214/SMDK/lib/qemu/qemu-8.1.50
TARGET_DIRS=x86_64-softmmu
HAVE_GDB_BIN=/usr/bin/gdb
SUBDIRS= contrib/plugins
PYTHON=/home/ejs1214/SMDK/lib/qemu/qemu-8.1.50/build-femu/pyvenv/bin/python3 -B
GENISOIMAGE=/usr/bin/genisoimage
MESON=/home/ejs1214/SMDK/lib/qemu/qemu-8.1.50/build-femu/pyvenv/bin/meson
NINJA=/usr/bin/ninja
EXESUF=
TCG_TESTS_TARGETS= x86_64-softmmu
